# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94620d8df0055ee9f4903f5f5cf5c08a"
name = "wetarseel"
handle = "wetarseel-1"
application_url = "https://district-bring-medline-involves.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/create", "checkouts/update" ]
  uri = "/webhooks/checkout/abandoned"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_checkouts,read_customers,read_orders"

[auth]
redirect_urls = [
  "https://district-bring-medline-involves.trycloudflare.com/auth/callback",
  "https://district-bring-medline-involves.trycloudflare.com/auth/shopify/callback",
  "https://district-bring-medline-involves.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
